FROM node:12
WORKDIR /server

# this is a bit of a hack to copy interfaces in
# normally the docker file should be inside the client directory
# with the interfaces published to a private NPM package/similar to keep things cleaner
COPY ./interfaces ./interfaces
COPY ./server ./server

WORKDIR /server/server

RUN yarn

# start app
CMD ["yarn", "start"]